version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  fastapi:
    build:
      context: ./fastapi-app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0

  celery-worker:
    build:
      context: ./celery-worker
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0

  celery-flower:
    build:
      context: ./celery-flower
    ports:
      - '5555:5555'  # Flower web interface
    depends_on:
      - redis
      - celery-worker
    environment:
      - REDIS_URL=redis://redis:6379/0
  


